
-- MySQL Script generated by MySQL Workbench
-- 03/19/16 13:08:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema warehouse
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `warehouse` DEFAULT CHARACTER SET utf8 ;
USE `warehouse` ;

-- -----------------------------------------------------
-- Table `warehouse`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warehouse`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contact_no` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warehouse`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warehouse`.`supplier` (
  `supplierId` INT NOT NULL AUTO_INCREMENT,
  `supplierName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `companyName` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `pincode` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`supplierId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warehouse`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orders` (
  `po_number` INT(11) NOT NULL AUTO_INCREMENT,
  `ordered_date` DATE NOT NULL,
  `delivery_date` DATE NOT NULL,
  `supplier_supplier_id` INT(11) NOT NULL,
  PRIMARY KEY (`po_number`),
  KEY `fk_orders_supplier` (`supplier_supplier_id`),
  CONSTRAINT `fk_orders_supplier` 
  FOREIGN KEY (`supplier_supplier_id`) 
  REFERENCES `supplier` (`supplierId`) 
  ON DELETE CASCADE 
  ON UPDATE CASCADE
) ENGINE=INNODB;

-- -----------------------------------------------------
-- Table `warehouse`.`order_details`
-- -----------------------------------------------------
CREATE TABLE `order_details` (
  `order_id` int(11) NOT NULL AUTO_INCREMENT,
  `product_name` varchar(45) NOT NULL,
  `barcode_number` varchar(45) NOT NULL,
  `description` varchar(45) NOT NULL,
  `quantity` int(11) NOT NULL,
  `weight` double NOT NULL,
  `amount` double NOT NULL,
  `orders_po_number` int(11) NOT NULL,
  PRIMARY KEY (`order_id`),
  KEY `fk_order_details_orders` (`orders_po_number`),
  CONSTRAINT `fk_order_details_orders` 
  FOREIGN KEY (`orders_po_number`) 
  REFERENCES `orders` (`po_number`) 
  ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
